apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::724338803814:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FPTEGOXECQE5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-06T14:12:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "862"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 86fc924e-b6e5-464a-a729-729cc88df9e0
